### ISSUE TITLE
🐞 swiperSlide 슬라이드 버튼 선택 시 전체선택 이슈

### ISSUE THREAD

**Issue by djswns7** [mighty-paws/Petstagram#44]
## 문제 상황
swiperSlide 슬라이드 버튼을 클릭하여 슬라이드 이동 시, 
드래그를 통한 전체선택을 한 것처럼 판정되는 이슈 발생

## 기타
![swiperSlide 전체선택 오류](https://user-images.githubusercontent.com/72201211/235211036-a6ba962c-0807-4b03-9d8d-6a2d2084b46c.gif)

**Comment by to06109** [comment]
해결해서 PR 했습니다. 늦어서 죄송합니다..!
