### ISSUE TITLE
🐞 [2023.04.22] 깃허브 레포지토리 이슈 템플릿 적용이 안되는 문제

### ISSUE THREAD

**Issue by to06109** [mighty-paws/Petstagram#6]
## 문제 상황
폴더구조가 잘못되어있는 것 같습니다. `.github`폴더 안에 이슈템플릿 폴더가 있어야 합니다.

우리 플젝 폴더구조
![image](https://user-images.githubusercontent.com/69625013/233788248-0e8711a8-352e-41e9-9cdc-8094d2ad542a.png)
올바른 이슈 템플릿 폴더구조
![image](https://user-images.githubusercontent.com/69625013/233788218-5d4c8162-f384-4b28-848b-8454aed637e4.png)

**Comment by parkilbeom** [comment]
저번에 폴더 구조 변경하다가 빠져 있었나 보네요 ㅎㅎ
